name = "back"
main = "src/index.ts"
compatibility_date = "2024-11-11"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "hono-practice"
database_id = "97fa49e8-7f93-4fbb-af03-f8faee40b34e"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1